import ReduxProvider from "@/redux/provider";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import SalesSocketProvider from "@/hooks/SalesSocketProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <ReduxProvider>
          <SalesSocketProvider>
          {children}
          </SalesSocketProvider>
          <ToastContainer position="top-right" autoClose={3000} />
        </ReduxProvider>
      </body>
    </html>
  );
}
