import ReduxProvider from "@/redux/provider";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { SocketProvider } from "@/hooks/useSalesSocket";

export const metadata = {
  title: "SHOP.CO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <ReduxProvider>
          <SocketProvider>
          {children}
          </SocketProvider>
          <ToastContainer position="top-right" autoClose={3000} />
        </ReduxProvider>
      </body>
    </html>
  );
}
